# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PDFToolBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1094, 771)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.file_list = QtWidgets.QListWidget(self.centralwidget)
        self.file_list.setGeometry(QtCore.QRect(40, 90, 511, 271))
        self.file_list.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.file_list.setObjectName("file_list")
        self.file_list_label = QtWidgets.QLabel(self.centralwidget)
        self.file_list_label.setGeometry(QtCore.QRect(270, 60, 31, 16))
        self.file_list_label.setObjectName("file_list_label")
        self.ocr_languages_list = QtWidgets.QListWidget(self.centralwidget)
        self.ocr_languages_list.setGeometry(QtCore.QRect(580, 90, 241, 271))
        self.ocr_languages_list.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.ocr_languages_list.setObjectName("ocr_languages_list")
        self.available_ocr_languages_label = QtWidgets.QLabel(self.centralwidget)
        self.available_ocr_languages_label.setGeometry(QtCore.QRect(630, 60, 171, 16))
        self.available_ocr_languages_label.setObjectName("available_ocr_languages_label")
        self.app_title_label = QtWidgets.QLabel(self.centralwidget)
        self.app_title_label.setGeometry(QtCore.QRect(480, 0, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.app_title_label.setFont(font)
        self.app_title_label.setTextFormat(QtCore.Qt.AutoText)
        self.app_title_label.setObjectName("app_title_label")
        self.file_browse_button = QtWidgets.QPushButton(self.centralwidget)
        self.file_browse_button.setGeometry(QtCore.QRect(40, 380, 141, 32))
        self.file_browse_button.setObjectName("file_browse_button")
        self.remove_selected_items_button = QtWidgets.QPushButton(self.centralwidget)
        self.remove_selected_items_button.setGeometry(QtCore.QRect(180, 380, 181, 32))
        self.remove_selected_items_button.setObjectName("remove_selected_items_button")
        self.clear_all_items_button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_all_items_button.setGeometry(QtCore.QRect(360, 380, 121, 32))
        self.clear_all_items_button.setObjectName("clear_all_items_button")
        self.actions_label = QtWidgets.QLabel(self.centralwidget)
        self.actions_label.setGeometry(QtCore.QRect(940, 60, 60, 16))
        self.actions_label.setObjectName("actions_label")
        self.merge_pdfs_button = QtWidgets.QPushButton(self.centralwidget)
        self.merge_pdfs_button.setGeometry(QtCore.QRect(890, 90, 151, 32))
        self.merge_pdfs_button.setObjectName("merge_pdfs_button")
        self.ocr_pdfs_button = QtWidgets.QPushButton(self.centralwidget)
        self.ocr_pdfs_button.setGeometry(QtCore.QRect(890, 150, 151, 32))
        self.ocr_pdfs_button.setObjectName("ocr_pdfs_button")
        self.extract_text_button = QtWidgets.QPushButton(self.centralwidget)
        self.extract_text_button.setGeometry(QtCore.QRect(890, 210, 151, 32))
        self.extract_text_button.setObjectName("extract_text_button")
        self.extract_annotations_button = QtWidgets.QPushButton(self.centralwidget)
        self.extract_annotations_button.setGeometry(QtCore.QRect(890, 270, 151, 32))
        self.extract_annotations_button.setObjectName("extract_annotations_button")
        self.clear_language_selections_button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_language_selections_button.setGeometry(QtCore.QRect(600, 380, 191, 32))
        self.clear_language_selections_button.setObjectName("clear_language_selections_button")
        self.console_text_box = QtWidgets.QTextEdit(self.centralwidget)
        self.console_text_box.setGeometry(QtCore.QRect(40, 470, 781, 231))
        self.console_text_box.setReadOnly(True)
        self.console_text_box.setObjectName("console_text_box")
        self.status_of_operations_label = QtWidgets.QLabel(self.centralwidget)
        self.status_of_operations_label.setGeometry(QtCore.QRect(360, 440, 131, 16))
        self.status_of_operations_label.setObjectName("status_of_operations_label")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(890, 670, 151, 32))
        self.exit_button.setObjectName("exit_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1094, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.file_list_label.setText(_translate("MainWindow", "Files"))
        self.available_ocr_languages_label.setText(_translate("MainWindow", "Available OCR Languages"))
        self.app_title_label.setText(_translate("MainWindow", "PDF Tool Box"))
        self.file_browse_button.setText(_translate("MainWindow", "Browse for Files"))
        self.remove_selected_items_button.setText(_translate("MainWindow", "Remove Selected Items"))
        self.clear_all_items_button.setText(_translate("MainWindow", "Clear All Items"))
        self.actions_label.setText(_translate("MainWindow", "Actions"))
        self.merge_pdfs_button.setText(_translate("MainWindow", "Merge PDFs"))
        self.ocr_pdfs_button.setText(_translate("MainWindow", "OCR PDFs"))
        self.extract_text_button.setText(_translate("MainWindow", "Extract Text"))
        self.extract_annotations_button.setText(_translate("MainWindow", "Extract Annotations"))
        self.clear_language_selections_button.setText(_translate("MainWindow", "Clear Language Selections"))
        self.status_of_operations_label.setText(_translate("MainWindow", "Status of Operations"))
        self.exit_button.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
